- name: Update apt cache
  apt:
    update_cache: yes

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Get hostname
  command: hostname
  register: hostname_output

- name: Show hostname
  debug:
    msg: "{{ hostname_output.stdout }}"