server_name: dev-server
server_environment: development
timezone: Asia/Kolkata

docker_enabled: true
monitoring_enabled: true

admin_user: devops

ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDTgF/MmB5ye548kQr0YB+cT1HXAEQXHxxUV/v7If8sSKf3GIScnaiCyMGXLB0SQDfmnOr9AP443JRzDmr2cE7jkBqgScqMzLQFfLfAZqLp/R5zEZ9t3wprKWPlEkBLY0o+uxnE1NqHJu9wM4hDqRLJL5GMHIJrCYDzVl/kSGh1dv0fsFWccuKxGUrRYgAVhZxjK8FomiHsn8r6sdw9mFbcY2P7/3qGgYXbizGg7rUypHUTMjVnkgdT3H2ouwsaCHBGaSOdb6VzZolErFo2kpenZLDfaHHVXGFItQ/04mE2/pT7IS0EdgAQmuz+FawZf9/JFm6vrTu8EjZfFToDqZ0YDv9xeEbTVJYESZgi0onNiztCjftLXagqJ2Nk6YRK2ZLaCUqm/tA9UsYp/2ZHXjhU8I6SwJAvHb6baKQcuv4zm7FD3QkJSLymSJtDZYczzi4qzXpiiTe8anjNdDD8Uh9CrObqqFHGmfvifJTRMG83ovFbgvLOhMguGzurL5MgcE= purvaa@Purva"

ssh_hardening_enabled: false