---
- name: Install docker
  apt:
    name: "{{ docker_package }}"
    state: present
    update_cache: yes
  notify: Restart Docker

- name: Enable Docker service
  service:
    name: docker
    state: started

- name: Verify Docker Installation
  command: docker --version
  register: docker_version

- name: show Docker Version
  debug:
    msg: "{{ docker_version.stdout }}"
